[phases.setup]
aptPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
  "cd server && npm install",
  "cd ../client && npm install"
]

[phases.build]
cmds = [
  "cd client && npm run build",
  "cp -r client/dist server/public"
]

[start]
cmd = "cd server && node server.js"